version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    volumes:
      - ./config/dispatcher:/config
  database:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.20.0
    volumes:
      - ./config/resources:/config
